// Do not edit directly, this file was auto-generated by npm run style.
// The canvas's mark.* colours as [r, g, b] (canvas can't read CSS custom properties).
export const MARK_INK = [34, 34, 34];
export const MARK_CROWD = [187, 187, 187];
export const MARK_FOCUS = [34, 34, 34];
export const MARK_EDGE = [120, 120, 120];
export const MARK_EDGE_HIGHLIGHT = [34, 34, 34];
export const MARK_SEARCH = [34, 34, 34];
export const MARK_HOP_0 = [34, 34, 34];
export const MARK_HOP_1 = [238, 102, 119];
export const MARK_HOP_2 = [68, 119, 170];
export const MARK_HOP_3 = [102, 204, 238];
export const MARK_HOP_4 = [187, 187, 187];
export const MARK_HOP_1_LABEL = [97, 12, 24];
export const MARK_HOP_2_LABEL = [21, 53, 84];
export const MARK_HOP_3_LABEL = [0, 58, 78];
export const MARK_HOP_4_LABEL = [51, 51, 51];
export const MARK_TRAIL_ACCENT = [238, 102, 119];
export const MARK_QUIZ_RIGHT = [34, 136, 51];
export const MARK_QUIZ_WRONG = [238, 102, 119];
export const MARK_CAREER = [68, 119, 170];
