// Do not edit directly, this file was auto-generated by npm run style.
// The canvas's mark.* colours as [r, g, b] (canvas can't read CSS custom properties).
export const MARK_INK = [255, 255, 255];
export const MARK_CROWD = [187, 187, 187];
export const MARK_FOCUS = [255, 255, 255];
export const MARK_EDGE = [120, 120, 120];
export const MARK_NETWORK_INK = [255, 255, 255];
export const MARK_ANCHOR_HALO = [252, 229, 255];
export const MARK_NETWORK_DIM = [167, 167, 167];
export const MARK_EDGE_HIGHLIGHT = [255, 255, 255];
export const MARK_SEARCH = [255, 255, 255];
export const MARK_HOP_0 = [255, 255, 255];
export const MARK_HOP_1 = [255, 255, 255];
export const MARK_HOP_2 = [163, 80, 97];
export const MARK_HOP_3 = [8, 156, 176];
export const MARK_HOP_4 = [63, 236, 115];
export const MARK_HOP_1_LABEL = [255, 245, 187];
export const MARK_HOP_2_LABEL = [250, 183, 196];
export const MARK_HOP_3_LABEL = [201, 235, 255];
export const MARK_HOP_4_LABEL = [199, 255, 219];
export const MARK_RACE_UNLINED = [55, 44, 63];
export const MARK_RACE_FIELD = [106, 99, 111];
export const MARK_LINE_HALO = [19, 5, 29];
export const MARK_TRAIL_ACCENT = [238, 102, 119];
export const MARK_QUIZ_RIGHT = [34, 136, 51];
export const MARK_QUIZ_WRONG = [238, 102, 119];
export const MARK_CAREER = [68, 119, 170];
